re-instate tag check requirement
docs were able to be published with my token so we are good to go

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -30,10 +30,10 @@ jobs:
         run: |
           _version_tag=$(git describe --tags)
           _cmake_version=v$(grep "^[ \t]*VERSION" CMakeLists.txt | sed 's/[^.0-9]*//g')
-          #if [[ "${_version_tag}" != "${_cmake_version}" ]]; then
-          #  echo "::error::Git version ${_version_tag} does not match CMake version ${_cmake_version}"
-          #  exit 1
-          #fi
+          if [[ "${_version_tag}" != "${_cmake_version}" ]]; then
+            echo "::error::Git version ${_version_tag} does not match CMake version ${_cmake_version}"
+            exit 1
+          fi
           echo ${_version_tag}
           echo "PROJECT_NUMBER = ${_version_tag}" >> docs/doxyfile
       - 
